[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CodecZstd = "6b39b394-51ab-5f42-8807-6242bab2b4c2"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Morton = "2a6d852e-3fac-5a38-885c-fe708af2d09e"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Zarr = "0a941bbe-ad1d-11e8-39d9-ab76183a1d99"
